// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	general: {
		/**
		 * V​a​a​t​a​a
		 */
		siteName: string
		/**
		 * A​ ​w​e​b​s​i​t​e​ ​t​o​ ​h​e​l​p​ ​I​r​a​n​i​a​n​ ​b​u​s​i​n​e​s​s​e​s​ ​r​e​a​c​h​ ​t​h​e​i​r​ ​c​u​s​t​o​m​e​r​s
		 */
		siteDescription: string
	}
}

export type TranslationFunctions = {
	general: {
		/**
		 * Vaataa
		 */
		siteName: () => LocalizedString
		/**
		 * A website to help Iranian businesses reach their customers
		 */
		siteDescription: () => LocalizedString
	}
}

export type Formatters = {}
