import { MealTypes } from "./types";

// mealTypes.ts
export const mealTypes: MealTypes = {
  breakfast: {
    foods: [
      {
        name: "Egg",
        score: 5,
        emoji: "🥚",
        calories: 78,
        fiber: 0,
        protein: 6,
        cholesterol: 186,
      },
      {
        name: "Bacon",
        score: -2,
        emoji: "🥓",
        calories: 54,
        fiber: 0,
        protein: 3,
        cholesterol: 9,
      },
      {
        name: "Pancakes",
        score: -3,
        emoji: "🥞",
        calories: 227,
        fiber: 1,
        protein: 6,
        cholesterol: 47,
      },
      {
        name: "Yogurt",
        score: 4,
        emoji: "🍶",
        calories: 150,
        fiber: 0,
        protein: 12,
        cholesterol: 15,
      },
      {
        name: "Fruit Bowl",
        score: 7,
        emoji: "🍓",
        calories: 100,
        fiber: 4,
        protein: 2,
        cholesterol: 0,
      },
      {
        name: "Donut",
        score: -5,
        emoji: "🍩",
        calories: 253,
        fiber: 1,
        protein: 4,
        cholesterol: 10,
      },
    ],
    calorieLimit: 600,
  },
  lunch: {
    foods: [
      {
        name: "Salad",
        score: 8,
        emoji: "🥗",
        calories: 200,
        fiber: 5,
        protein: 8,
        cholesterol: 0,
      },
      {
        name: "Sandwich",
        score: 3,
        emoji: "🥪",
        calories: 300,
        fiber: 3,
        protein: 15,
        cholesterol: 30,
      },
      {
        name: "Pizza",
        score: -3,
        emoji: "🍕",
        calories: 285,
        fiber: 2,
        protein: 12,
        cholesterol: 17,
      },
      {
        name: "Sushi",
        score: 6,
        emoji: "🍣",
        calories: 350,
        fiber: 1,
        protein: 20,
        cholesterol: 40,
      },
      {
        name: "Burger",
        score: -4,
        emoji: "🍔",
        calories: 354,
        fiber: 1,
        protein: 17,
        cholesterol: 53,
      },
      {
        name: "Fruit",
        score: 5,
        emoji: "🍎",
        calories: 95,
        fiber: 4,
        protein: 1,
        cholesterol: 0,
      },
    ],
    calorieLimit: 800,
  },
  dinner: {
    foods: [
      {
        name: "Steak",
        score: -1,
        emoji: "🥩",
        calories: 405,
        fiber: 0,
        protein: 62,
        cholesterol: 146,
      },
      {
        name: "Fish",
        score: 7,
        emoji: "🐟",
        calories: 200,
        fiber: 0,
        protein: 40,
        cholesterol: 80,
      },
      {
        name: "Pasta",
        score: -2,
        emoji: "🍝",
        calories: 400,
        fiber: 3,
        protein: 14,
        cholesterol: 0,
      },
      {
        name: "Chicken",
        score: 5,
        emoji: "🍗",
        calories: 300,
        fiber: 0,
        protein: 50,
        cholesterol: 100,
      },
      {
        name: "Vegetables",
        score: 8,
        emoji: "🥦",
        calories: 50,
        fiber: 4,
        protein: 3,
        cholesterol: 0,
      },
      {
        name: "Ice Cream",
        score: -5,
        emoji: "🍨",
        calories: 250,
        fiber: 1,
        protein: 4,
        cholesterol: 30,
      },
    ],
    calorieLimit: 1000,
  },
};
